const PLATFORM_CATEGORY_DEFINITIONS = [
  {
    id: 'Drejtësia',
    label: 'Drejtësia',
    icon: 'fa-scale-unbalanced',
    keywords: [
      'drejtes',
      'gjykat',
      'prokuror',
      'prokurori',
      'ligj',
      'korrupsion',
      'sundim',
      'veting',
      'kushtetu',
      'penal',
    ],
  },
  {
    id: 'Ekonomia',
    label: 'Ekonomia',
    icon: 'fa-chart-line',
    keywords: [
      'ekonomi',
      'biznes',
      'investim',
      'treg',
      'buxhet',
      'tatim',
      'dogan',
      'ndermarr',
      'industri',
      'prodhim',
      'eksport',
      'import',
      'inflacion',
      'pag',
      'punesim',
    ],
  },
  {
    id: 'Siguria',
    label: 'Siguria',
    icon: 'fa-shield-halved',
    keywords: [
      'siguri',
      'polici',
      'forc',
      'mbrojt',
      'ushtri',
      'kufi',
      'inteligjenc',
      'terroriz',
      'krim',
      'rend',
    ],
  },
  {
    id: 'Mirëqenia',
    label: 'Mirëqenia',
    icon: 'fa-hands-holding-child',
    keywords: [
      'mireqen',
      'social',
      'pension',
      'ndihm',
      'familj',
      'lehon',
      'femij',
      'barazi',
      'streh',
      'varfer',
      'shtes',
    ],
  },
  {
    id: 'Shëndetësia',
    label: 'Shëndetësia',
    icon: 'fa-heart-pulse',
    keywords: [
      'shendet',
      'spital',
      'mjek',
      'pacient',
      'klinike',
      'klinika',
      'barna',
      'barn',
      'sigurim shendetesor',
      'ambulanc',
      'terapi',
      'farmaci',
    ],
  },
  {
    id: 'Arsimi',
    label: 'Arsimi',
    icon: 'fa-graduation-cap',
    keywords: [
      'arsim',
      'shkoll',
      'universitet',
      'student',
      'mesim',
      'profesor',
      'nxenes',
      'akreditim',
      'curricul',
      'bursa',
    ],
  },
  {
    id: 'Infrastruktura',
    label: 'Infrastruktura',
    icon: 'fa-bridge-water',
    keywords: [
      'rrug',
      'infrastruktur',
      'ndertim',
      'transport',
      'hekurudh',
      'autostrad',
      'ure',
      'ujesjell',
      'kanaliz',
      'dig',
    ],
  },
  {
    id: 'Inovacioni',
    label: 'Inovacioni',
    icon: 'fa-microchip',
    keywords: [
      'inovacion',
      'teknologj',
      'digjital',
      'start up',
      'startup',
      'software',
      'platform',
      'automatiz',
      'inteligjenc artificiale',
      'robot',
      'research',
    ],
  },
  {
    id: 'Turizmi',
    label: 'Turizmi',
    icon: 'fa-mountain-sun',
    keywords: [
      'turiz',
      'hotel',
      'resort',
      'vizitor',
      'destinacion',
      'bjeshk',
      'muze',
      'trashgimi',
      'guid',
    ],
  },
  {
    id: 'Diaspora',
    label: 'Diaspora',
    icon: 'fa-earth-europe',
    keywords: [
      'diaspor',
      'mergat',
      'bashkatdhet',
      'migrim',
      'riatdhes',
      'votim nga jashte',
      'konsull',
      'ambasad',
    ],
  },
  {
    id: 'Energjia',
    label: 'Energjia',
    icon: 'fa-solar-panel',
    keywords: [
      'energji',
      'rryme',
      'korporata energjetike',
      'keq',
      'termocentral',
      'solar',
      'ere',
      'hidro',
      'eficienc',
      'ngrohje',
      'gaz',
    ],
  },
  {
    id: 'Sporti',
    label: 'Sporti',
    icon: 'fa-futbol',
    keywords: [
      'sport',
      'futboll',
      'basketboll',
      'hendboll',
      'federat',
      'stadion',
      'palestr',
      'olimpik',
      'atlet',
    ],
  },
  {
    id: 'Arti',
    label: 'Arti',
    icon: 'fa-palette',
    keywords: [
      'art',
      'kultur',
      'teater',
      'film',
      'muzik',
      'bibliotek',
      'galeri',
      'festival',
      'artist',
    ],
  },
  {
    id: 'Politika e Jashtme',
    label: 'Politika e Jashtme',
    icon: 'fa-globe',
    keywords: [
      'politike e jashtme',
      'diploma',
      'diplomat',
      'njohje',
      'kombet e bashkuara',
      'nato',
      'integrim evropian',
      'bashkimi evropian',
      'marredhenie nderkombetare',
      'dialog',
      'serbi',
    ],
  },
];

export const PLATFORM_CATEGORIES = PLATFORM_CATEGORY_DEFINITIONS.map(({ id, label, icon }) => ({
  id,
  label,
  icon,
}));

export const CATEGORIES_WITH_ALL = [
  { id: 'all', label: 'Të Gjitha', icon: 'fa-layer-group' },
  ...PLATFORM_CATEGORIES,
];

export const DEPUTY_TOPIC_TAXONOMY = PLATFORM_CATEGORY_DEFINITIONS.map(({ id, label, keywords }) => ({
  topicId: id,
  label,
  keywords: [...keywords],
}));
